// ---
// THIS FILE IS AUTO-GENERATED BY WEA (Web Elements Analyzer).
// DO NOT EDIT MANUALLY — your changes will be overwritten.
// ---
interface CustomElementsLocal {
	/**
	 * ```jsx
	 * class JsonSchemaFormWebawesome extends JsonSchemaFormElement (<jsf-webawesome>)
	 * ```
	 * ---
	 * @property `widgets` — {`typeof widgets`}
	 */
	'jsf-webawesome': {
		elementClass: HTMLElementTagNameMap['jsf-webawesome'];
		properties: {
			widgets?: HTMLElementTagNameMap['jsf-webawesome']['widgets'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
}
interface GlobalCss {
	properties: {};
}
declare global {
	interface HTMLElementTagNameMap {
		'jsf-webawesome': import('./../form.js').JsonSchemaFormWebawesome;
	}
	interface GlobalEventHandlersEventMap {}
}
import type { CustomElementsExternals } from './web-elements.exts';
interface CustomElements extends CustomElementsLocal, CustomElementsExternals {}
export type {
	CustomElements,
	CustomElementsLocal,
	GlobalCss,
	CustomElementsExternals,
};

import type * as vueTypes from 'vue';

export type StyleValue<CeCssProperties> =
	| (CeCssProperties & vueTypes.CSSProperties)
	| false
	| null
	| string
	| undefined
	| vueTypes.StyleValue[];

export type VueElementsFrom<CustomElements extends Record<string, any>> = {
	[TagName in keyof CustomElements]: vueTypes.DefineComponent<
		AddPrefixToKeys<ConvertKeysToPascal<EmitsFrom<CustomElements[TagName]>>> &
			CustomElements[TagName]['attributes'] &
			CustomElements[TagName]['properties'] &
			Omit<vueTypes.HTMLAttributes, 'style' | `on${string}`> &
			Partial<
				AddCurrentTarget<
					vueTypes.Events,
					CustomElements[TagName]['elementClass']
				>
			> & {
				style?: StyleValue<CustomElements[TagName]['cssProperties']>;
			}
	>;
};

type AddCurrentTarget<T, Host> = {
	[K in keyof T]: (
		e: Omit<T[K], 'currentTarget'> & { currentTarget: Host },
	) => void;
};

type ConvertKeysToPascal<T extends Record<string, any>> = {
	[K in keyof T as KebabToPascal<K & string>]: T[K];
};

type EmitsFrom<ElementInfo extends { elementClass: any; events: any }> = {
	[KeyName in keyof ElementInfo['events']]: (
		event: Omit<
			NonNullable<ElementInfo['events'][KeyName]>,
			'currentTarget'
		> & {
			currentTarget: ElementInfo['elementClass'];
		},
	) => void;
};

type KebabToPascal<S extends string> = S extends `${infer First}-${infer Rest}`
	? `${Capitalize<First>}${Capitalize<KebabToPascal<Rest>>}`
	: S;

declare module 'vue' {
	interface GlobalComponents extends VueElementsFrom<CustomElements> {}
}

export type AddPrefixToKeys<
	T extends Record<string, any>,
	Prefix extends string = 'on',
> = {
	[K in keyof T as `${Prefix}${K & string}`]: T[K];
};

export type ReactElementsFrom<CustomElements extends Record<string, any>> = {
	[TagName in keyof CustomElements]: CustomElements[TagName]['attributes'] &
		CustomElements[TagName]['properties'] &
		EventsPrefixed<
			CustomElements[TagName]['events'],
			'on',
			CustomElements[TagName]['elementClass']
		> &
		React.DetailedHTMLProps<
			React.HTMLAttributes<CustomElements[TagName]['elementClass']>,
			CustomElements[TagName]['elementClass']
		> & {
			style?: CustomElements[TagName]['cssProperties'] & React.CSSProperties;
		};
};

declare module 'react' {
	namespace JSX {
		interface IntrinsicElements extends ReactElementsFrom<CustomElements> {}
	}
}

export type EventsPrefixed<
	EventMap extends Record<string, Event>,
	Prefix extends string = '',
	Element extends HTMLElement = HTMLElement,
> = {
	[EventName in keyof EventMap as `${Prefix}${EventName & string}`]: (
		event: TypedEvent<Element, EventMap[EventName]>,
	) => void;
};
export type TypedEvent<Element, _Event extends Event> = _Event & {
	currentTarget: Element;
};

declare module 'jsx-forge/jsx-runtime' {
	namespace JSX {
		interface IntrinsicElements
			extends JSX.MappedCustomElements<CustomElements, JSX.BaseHTMLElement> {}
	}
}
